org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# --- Versiones (NeoForge NO admite comodines: pon una version exacta, ver https://mvnrepository.com/artifact/net.neoforged/neoforge) ---
minecraft_version=26.2
neo_version=26.2.0.64

# --- Datos del mod ---
mod_id=gamersystem
mod_name=Gamer System
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.gamersystem
mod_authors=TuNombre
mod_description=Mod de sistema RPG inspirado en el genero "gamer": nivel, stats, MP, habilidades, zonas protegidas y de entrenamiento, y mazmorra con mobs vainilla.
